In [2]:
import pandas as pd

# Read the results file
df = pd.read_csv('../results/mistral/top_train+prompt.csv')

# Round numeric columns to 3 decimal places
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].round(3)

# Remove count and skipped columns
cols_to_drop = [col for col in df.columns if 'count' in col.lower() or 'skipped' in col.lower() or 'pairs' in col.lower()]
df_clean = df.drop(columns=cols_to_drop)

# Display the table
df_clean

,axis,vector_type,layer,coeff,bbq_accuracy,mmlu_accuracy,bbq_s_dis,bbq_s_amb,mmlu_total_questions,mmlu_correct_answers,crows_bias_type,crows_bias_score,crows_stereo_bias_score,crows_antistereo_bias_score,stereoset_ss_score,stereoset_lm_score,stereoset_icat_score
0,age,train+prompt,14,1.8,0.673,0.466,0.560,0.202,969,452,age,0.747,0.795,0.500,NaN,NaN,NaN
1,appearance,train+prompt,13,1.6,0.623,0.481,0.333,0.123,969,466,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,disability,train+prompt,14,1.6,0.660,0.463,0.433,0.165,969,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gender,train+prompt,13,1.8,0.670,0.451,0.246,0.071,969,437,gender,0.622,0.679,0.534,63.984,86.720,62.467
4,nationality,train+prompt,13,1.6,0.693,0.481,0.675,0.263,969,466,nationality,0.616,0.601,0.818,NaN,NaN,NaN
5,race,train+prompt,14,2.0,0.645,0.471,0.509,0.204,969,456,race-color,0.690,0.698,0.605,61.507,89.474,68.883
6,religion,train+prompt,13,1.6,0.580,0.474,0.156,0.073,969,459,religion,0.724,0.727,0.667,45.860,91.083,83.541
7,socioeconomic,train+prompt,13,1.6,0.653,0.457,0.096,0.028,969,443,socioeconomic,0.738,0.771,0.400,NaN,NaN,NaN